### PR TITLE
refactor: 修正拼写错误 & 替换图标

### PR DESCRIPTION
**Pull request by Hakuin123**
## Description
- 修正 'sticker_pane**l**_set_button_icon' 的拼写错误
- 替换表情菜单图标为 [Material Symbols](https://fonts.google.com/icons)，统一图标设计

## Issues Fixed or Closed by This PR
N?A

## Check List

- [x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Comment by cinit** [comment]
要不你换 SVG 吧，用 `android:tint="?attr/colorControlNormal"`

**Comment by Hakuin123** [comment]
啊，抱歉忘记深色模式了）

换SVG的话…不是很懂Android开发 _(:з」∠)_

**Comment by cinit** [comment]
你在哪找的图标? https://github.com/google/material-design-icons 吗？

**Comment by Hakuin123** [comment]
https://fonts.google.com/icons

**Comment by cinit** [comment]
> https://fonts.google.com/icons

@Hakuin123 这个网站有矢量图标的，如果你是 zip 下载的，在不带后缀的 drawable 文件夹里，是 xml 文件。

**Pull request closed without merging**
