### PR TITLE
Update StartupRoutine.java

### PR DESCRIPTION
**Pull request by zero-rp**
某些虚拟xposed环境下内部的资源加载会异常

# Title Here

## Check List

- [x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Comment by duzhaokun123** [comment]
@zero-rp 吞异常不报是坏行为 而且这是 error 我们没有能力处理 error

**Comment by zero-rp** [comment]
> @zero-rp 吞异常不报是坏行为 而且这是 error 我们没有能力处理 error

正是因为无法处理所以才给屏蔽了,不屏蔽直接导致插件加载失败,经过分析这个模块的代码和QA的代码发现这个初始化无关紧要,经过测试在执行异常的情况下插件也能正常工作,不忽略异常插件就直接挂掉了,

**Comment by duzhaokun123** [comment]
@zero-rp 那他就应该加载失败

所以是什么 xposed 框架

**Comment by zero-rp** [comment]
> 

VirtualApp,导致异常的代码是那个模块里面
fun initZygote(startupParam: IXposedHookZygoteInit.StartupParam) {
        modulePath = startupParam.modulePath
        moduleRes = XModuleResources.createInstance(modulePath, null)
    }
XModuleResources这个class在这个环境下找不到

**Comment by huajijam** [comment]
问题非本模块引起 请联系您所使用的xposed API
https://api.xposed.info/reference/android/content/res/XModuleResources.html

**Comment by huajijam** [comment]
@zero-rp

**Comment by keta1** [comment]
再不扔掉这种垃圾东西 xposed哪有美好的生态

**Pull request closed without merging**
