### PR TITLE
Update TransactionHelper.kt

### PR DESCRIPTION
**Pull request by cnrenil**
# Title Here

## Check List

- [ ] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [ ] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Comment by cnrenil** [comment]
Close by error

**Comment by qwq233** [comment]
你在干什么

**Comment by cnrenil** [comment]
> 你在干什么

我的错误，想要白嫖GitHub Actions，pr错了上游

**Comment by cnrenil** [comment]
> 你在干什么

https://support.github.com/request

打开这个可以删除这个二逼的pr😅

Remove data from a repository I own or control然后根据ai提示来就行

**Pull request closed without merging**
