### PR TITLE
[merged] feat: Remove OpenGroupChangeMsgPushSettings tip and PasteHere tip （Need to sign by maintainers)

### PR DESCRIPTION
**Pull request by MoonLeeeaf**
# 移除群聊“打开消息推送设置”以及输入框“点击粘贴”

## Description

参考 #889 #890 各位大佬有兴趣完善的话请一定要看完这俩Issue，里面有我分析的一些思路供诸位参考

本功能仅作粗略实现，仍需完善

由于无法签名，因此需要另人帮助提交，若确认提交请直接关闭此PR
Screenshot_2024-04-06-23-57-36-930_com termux

## Issues Fixed or Closed by This PR

#889 #890 

## Check List

未经测试（没办法进行），功能实现思路均在上面的Issue中，因此我无法保证

- [ ] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

这几天实在是被惹毛了，所以才急着做功能，还麻烦各位帮我签名了，谢谢大家（

### CODE REVIEW

**Comment by cinit** [comment]
你看一下 https://github.com/cinit/QAuxiliary/commit/69af3a039c497bfb1ad69c79166f35efc22f7cf2

**Comment by MoonLeeeaf** [comment]
感谢大佬，我现在去测试下

**Comment by MoonLeeeaf** [comment]
> 你看一下 [69af3a0](https://github.com/cinit/QAuxiliary/commit/69af3a039c497bfb1ad69c79166f35efc22f7cf2)

辛苦作者大大了
我刚刚简单进行了测试，所有功能均正常运作！
(｡･ω･｡)

**Comment by cinit** [comment]
@MoonLeeeaf 另外，你开 PR 的时候建议你单开一个 branch, 命名为 patch-xxx, 并使你 patch 分支和 origin/main 保持一致，以便 fast-forward merge.

**Comment by MoonLeeeaf** [comment]
> @MoonLeeeaf 另外，你开 PR 的时候建议你单开一个 branch, 命名为 patch-xxx, 并使你 patch 分支和 origin/main 保持一致，以便 fast-forward merge.

收到
谢大佬指点♡

**Pull request closed without merging**
