### PR TITLE
feat: add HideClockInTip

### PR DESCRIPTION
**Pull request by HdShare**
# HideClockInTip

## Description
对提示消息中的打卡消息进行简单隐藏，不太会DexKit，就单纯适配了8.9.88(4852)
// .method private final t1()Lcom/tencent/mobileqq/aio/msglist/holder/component/graptips/GrayTipsTextView;

## Check List

- [x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Comment by cinit** [comment]
并非所有情况都适合用 dexkit, 在本案中你可以按返回值类型以及修饰符唯一确定目标方法。
```kotlin
grayTipsClass.declaredMethods.single {
    it.returnType == xxx && it.modifier == xxx && 参数类型...
}
```

**Comment by cinit** [comment]
另外 PR 建议 rebase 一下避免出现 [Merge remote-tracking branch 'origin/main'](https://github.com/cinit/QAuxiliary/pull/927/commits/9e59a8d1a5f14c72fb3fb98ae05039ad42253037) 之类不线性历史的东西。

**Comment by HdShare** [comment]
> 另外 PR 建议 rebase 一下避免出现 [Merge remote-tracking branch 'origin/main'](https://github.com/cinit/QAuxiliary/pull/927/commits/9e59a8d1a5f14c72fb3fb98ae05039ad42253037) 之类不线性历史的东西。

ok，我重新改改

**Comment by HdShare** [comment]
> 并非所有情况都适合用 dexkit, 在本案中你可以按返回值类型以及修饰符唯一确定目标方法。

我想要在 com/tencent/mobileqq/app/ 类下
搜索一个方法，名为onUpdate，且包含字符串target_desc
使用Dexkit大概怎么编写，我不太会用，写的貌似有问题

> ```kotlin
> data object HdMethodFakePhone : DexKitTarget.UsingStr() {
>     override val findMethod = true
>     override val traitString = arrayOf("target_desc")
>     override val declaringClass = "com/tencent/mobileqq/app/"
>     override val filter = filter@{ it: DexMethodDescriptor -> it.name == "onUpdate" }
> }
> ```

**Pull request closed without merging**
