### PR TITLE
 fix: RemoveSuperQQShow on 8.9.5

### PR DESCRIPTION
**Pull request by lliioollcn**
# Title Here

 fix: RemoveSuperQQShow on 8.9.5

## Description

 fix: RemoveSuperQQShow on 8.9.5

## Issues Fixed or Closed by This PR
#140 
## Check List

- [x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Review by NextAlone — APPROVED** [review]
能跑就行

**Comment by lliioollcn** [comment]
> 能跑就行

啊？

**Comment by KyuubiRan** [comment]
z？wsmatw

**Review by keta1 — APPROVED** [review]
好

**Review by qwq233 — APPROVED** [review]

**Comment by teble** [comment]
好！

**Pull request merged**
